name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 将 'main' 替换为默认分支名称（例如 'master'）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all history
        run: git fetch --prune --unshallow

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 安装依赖
        run: npm ci

      - name: 构建
        run: npm run build


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: . 
